### ISSUE TITLE
Réaliser une icône

### ISSUE THREAD

**Issue by jpcima** [linuxmao-org/sysexxer-ng#1]

**Comment by trebmuh** [comment]
Proposition

![sysexxer-ng](https://user-images.githubusercontent.com/8705846/47616301-1de3ad80-dabb-11e8-96a7-92a89b7bb5cf.png)

Crédits:
- https://en.wikipedia.org/wiki/MIDI#/media/File:MIDI_connector2.svg
- symbôle mâle/femelle dans le domaine public (https://fr.wikipedia.org/wiki/%E2%99%82#/media/File:Mars_symbol.svg et https://fr.wikipedia.org/wiki/%E2%99%80#/media/File:Venus_symbol.svg)

**Comment by jpcima** [comment]
Je prends ! j'essaierai éventuellement de produire une version colorée. Tu as le svg ?
Aussi c'est envisageable de faire des constructions à base des emojis en svg, c'est ainsi que je fais d'habitude (ex FreeMajor).

Fichiers SVG https://github.com/googlei18n/noto-emoji/tree/master/svg
Référence https://unicode.org/emoji/charts/full-emoji-list.html

**Comment by trebmuh** [comment]
J'ai tout fait directement dans GIMP en png. Pas de SVG donc.

**Comment by jpcima** [comment]
Bon je verrai plus tard pour retoucher ça et je vais accepter ceci comme icône temporaire.
Tu veux me commit une version optipng de cette image, dans `resources/application` ?

**Comment by trebmuh** [comment]
Fait dans https://github.com/linuxmao-org/sysexxer-ng/commit/15dc2875124b9be33016828ab7a8010a4955a5f3

Je ferme ici.
