### ISSUE TITLE
Does not compile - utility.cc.o Archlinux

### ISSUE THREAD

**Issue by kamelie1706** [linuxmao-org/sysexxer-ng#11]
Fail to compile on Archlinux

/sysexxer-ng/sources/utility.cc:8:44: erreur: le type retourné « std::string » {aka « class std::__cxx11::basic_string<char> »} est incomplet
    8 | std::string astrprintf(const char *fmt, ...)
      |                                            ^
/sysexxer-ng/sources/utility.cc:8:13: erreur: rend ambigüe la nouvelle déclaration de « void astrprintf(const char*, ...) »
    8 | std::string astrprintf(const char *fmt, ...)
      |             ^~~~~~~~~~
Dans le fichier inclus depuis /sysexxer-ng/sources/utility.cc:6:
/sysexxer-ng/sources/utility.h:22:13: note: ancienne déclaration « std::string astrprintf(const char*, ...) »
   22 | std::string astrprintf(const char *fmt, ...);
      |             ^~~~~~~~~~
sysexxer-ng/sources/utility.cc: Dans la fonction « void astrprintf(const char*, ...) »:
/sysexxer-ng/sources/utility.cc:12:17: erreur: la variable « std::string string » a un initialiseur mais a un type incomplet
   12 |     std::string string = vastrprintf(fmt, ap);
      |                 ^~~~~~
/sysexxer-ng/sources/utility.cc:12:45: erreur: utilisation invalide du type incomplet « std::string » {aka « class std::__cxx11::basic_string<char> »}
   12 |     std::string string = vastrprintf(fmt, ap);
      |                                             ^
Dans le fichier inclus depuis /usr/include/c++/10.1.0/iosfwd:39,
                 depuis /usr/include/c++/10.1.0/memory:74,
                 depuis /home/cyril/AUR/sysexxer-ng/sources/utility.h:6,
                 depuis /home/cyril/AUR/sysexxer-ng/sources/utility.cc:6:
/usr/include/c++/10.1.0/bits/stringfwd.h:74:11: note: déclaration de « std::string » {aka « class std::__cxx11::basic_string<char> »}
   74 |     class basic_string;
      |           ^~~~~~~~~~~~
/sysexxer-ng/sources/utility.cc: Au niveau global:
/sysexxer-ng/sources/utility.cc:17:52: erreur: le type retourné « std::string » {aka « class std::__cxx11::basic_string<char> »} est incomplet
   17 | std::string vastrprintf(const char *fmt, va_list ap)
      |                                                    ^
/sysexxer-ng/sources/utility.cc:17:13: erreur: rend ambigüe la nouvelle déclaration de « void vastrprintf(const char*, __va_list_tag*) »
   17 | std::string vastrprintf(const char *fmt, va_list ap)
      |             ^~~~~~~~~~~
Dans le fichier inclus depuis /sysexxer-ng/sources/utility.cc:6:
/sysexxer-ng/sources/utility.h:23:13: note: ancienne déclaration « std::string vastrprintf(const char*, __va_list_tag*) »
   23 | std::string vastrprintf(const char *fmt, va_list ap);
      |             ^~~~~~~~~~~
make[2]: *** [CMakeFiles/sysexxer-ng.dir/build.make:174 : CMakeFiles/sysexxer-ng.dir/sources/utility.cc.o] Erreur 1
make[1]: *** [CMakeFiles/Makefile2:268 : CMakeFiles/sysexxer-ng.dir/all] Erreur 2
make: *** [Makefile:150 : all] Erreur 2

**Comment by jpcima** [comment]
Hello, hopefully it will be resolved by this quick fix e6fc8b3

**Comment by kamelie1706** [comment]
Perfect!
