### ISSUE TITLE
cannot build

### ISSUE THREAD

**Issue by tjingboem** [linuxmao-org/sysexxer-ng#15]
trying to build from a Linux Mint with Jack, i get:

```
--   Found jack, version 1.9.20
CMake Error at CMakeLists.txt:57 (add_subdirectory):
  The source directory

    /media/menno/datae/temp6/sysexxer-ng-master/thirdparty/fmidi

  does not contain a CMakeLists.txt file.


-- Configuring incomplete, errors occurred!
```
And, indeed, i do not see a CMakeLists.txt file.
Am i doingsomething wrong?

**Comment by trebmuh** [comment]
Hi
Are you trying to build from a fresh git clone? If so, did you clone it with the `--recursive` command line option?

**Comment by tjingboem** [comment]
ah yes of course, my bad...i downloaded this repo as a zip file, not via git.
I will try again.
Thanks

**Comment by trebmuh** [comment]
hi @tjingboem : did that worked?

**Comment by tjingboem** [comment]
Merci pour demander. 
in the meanwhile i figured i could use Reaper to record my sysex messages, and play it back. Still have to try it out though.

So i did not follow the route of installing git and building sysexxer-ng.
If Reaper doesn't work out the way i want it, i will get back here and try again :)

**Comment by trebmuh** [comment]
You're welcome. Thanks for answering quickly and for the French start! :)
For info, sysexxer-ng is packaged in the [LibraZiK](https://librazik.tuxfamily.org/) project.
LibraZiK is based on Debian and there is a little chance that the package can be working under Mint.
Although it is not advisable to mix software sources in this way, this might be working for this special software.
That said, use at your own risk!

**Comment by tjingboem** [comment]
Mint is based on Ubuntu...that is based on Debian...yes it is a remote cousin

**Comment by trebmuh** [comment]
That's why I mentioned it to you.
Let me know if you want to try that.
