### ISSUE TITLE
missing file

### ISSUE THREAD

**Issue by farvardin** [linuxmao-org/sysexxer-ng#8]
I've clone the repo then I've done:  git submodule update --init

It seems libfmt-dev is required, but after I've added it, during compilation I got:

[ 22%] Building CXX object thirdparty/fmidi/CMakeFiles/fmidi.dir/sources/fmidi/file/read_smf.cc.o
In file included from /temp/github/sysexxer-ng/thirdparty/fmidi/sources/fmidi/file/read_smf.cc:11:0:
/usr/include/fmt/format.h:4007:11: fatal error: format.cc: No such file or directory
  # include "format.cc"
           ^~~~~~~~~~~
compilation terminated.

**Comment by farvardin** [comment]
and without libfmt-dev, I get this error:

/temp/github/sysexxer-ng/thirdparty/fmidi/sources/fmidi/file/read_smf.cc:11:10: fatal error: fmt/format.h: No such file or directory
  #include <fmt/format.h>

**Comment by jpcima** [comment]
`fmt` is a submodule of the `fmidi` submodule.
Try: `git submodule update --init --recursive`

**Comment by trebmuh** [comment]
:heart: 'zêtes meugnon à vous causer anglais :wink:

**Comment by farvardin** [comment]
ah merci, effectivement c'était bien à cause de ça, désolé :(
J'ai pu compiler correctement sysexxer-ng

**Comment by jpcima** [comment]
J'écrirai une note dans le fichier `REAME.md`.
