### ISSUE TITLE
Version 1.0

### ISSUE THREAD

**Issue by jpcima** [linuxmao-org/sysexxer-ng#9]
:us: Release the first stable version of Sysexxer-NG.

:fr: Livrer la première version stable de Sysexxer-NG.

**Comment by trebmuh** [comment]
[Fait ici](https://github.com/linuxmao-org/sysexxer-ng/releases/tag/v1.0).
On ferme @jpcima ?

**Comment by jpcima** [comment]
Oui car la version 1.0 est désormais prête, et publiée. :+1:
